-- FK's--
ALTER TABLE DB_TASK ADD CONSTRAINT FK_TASK_ROOM FOREIGN KEY (roomId) REFERENCES DB_ROOM(roomId);
ALTER TABLE DB_CHAT ADD CONSTRAINT FK_CHAT_ROOM FOREIGN KEY (roomId) REFERENCES DB_ROOM(roomId);

ALTER TABLE DB_ROOM ADD CONSTRAINT FK_USER_ROOM FOREIGN KEY (userId) REFERENCES DB_USER(userId);
ALTER TABLE DB_PASSWORD ADD CONSTRAINT FK_USER_PASSWORD FOREIGN KEY (userId) REFERENCES DB_USER(userId);
